sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out_new
    username: root
    password: 070608

  redis:
    host: localhost
    port: 6379
    database: 2

